# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def clientAPI
  pod 'Contentful', '~> 5.1.2'
  pod 'Kingfisher'
end

target 'MarleySpoon' do
  use_frameworks!
  clientAPI
end
